p8105\_hw3\_qs2200
================
Qi Shao
10/7/2018

Problem 1
=========

**1. Import and clean the dataset.**

``` r
brfss_df = p8105.datasets::brfss_smart2010 %>%
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  mutate(response = factor(response, levels = c("Excellent", "Very good", "Good","Fair", "Poor")))%>%
  rename(state = locationabbr) %>%
  arrange(response) 

##filter(topic == "Overall Health", response ==c("Excellent", "Very good", "Good","Fair", "Poor"))
##why can't we filter the rows which response is excellent to poor
```

**2. In 2002, which states were observed at 7 locations?**

``` r
brfss_state = 
  group_by(brfss_df , state) %>%
  summarize(n = n_distinct(locationdesc)) %>%
  filter(n == 7)
```

The 7 states CT, MT, NH, NM, OR, TN, UT were observed at 7 locations.

**3. Make a “spaghetti plot” that shows the number of observations in each state from 2002 to 2010.**

``` r
brfss_spa =
  group_by(brfss_df, state,year) %>%
  summarize(n_obs = n())

ggplot(brfss_spa, aes(x = year, y = n_obs, color = state))+
  geom_line()+geom_point()+
  labs(x = "Year",
    y = "Number of observations")
```

![](p8105_hw3_qs2200_files/figure-markdown_github/problem%201.3-1.png) **4. Make a table showing, for the years 2002, 2006, and 2010, the mean and standard deviation of the proportion of “Excellent” responses across locations in NY State.**

``` r
brfss_tb =
  filter(brfss_df, year %in% c(2002, 2006, 2010),
         state == "NY",
         response == "Excellent")%>%
  group_by(year) %>%
  summarize(mean_prop = mean(data_value), 
            sd_prop = sd(data_value, na.rm  = TRUE))
  knitr::kable(brfss_tb, digits = 2)
```

|  year|  mean\_prop|  sd\_prop|
|-----:|-----------:|---------:|
|  2002|       24.04|      4.49|
|  2006|       22.53|      4.00|
|  2010|       22.70|      3.57|

**5.For each year and state, compute the average proportion in each response category (taking the average across locations in a state). Make a five-panel plot that shows, for each response category separately, the distribution of these state-level averages over time.**

``` r
aver_exce = 
  filter(brfss_df, response == "Excellent") %>%
  group_by(state,year) %>%
  summarize(mean_prop = mean(data_value)) %>%
  ggplot(aes(x = year, y = mean_prop, color = state)) +
  geom_line() +
  theme(legend.position = "none")

aver_very = 
  filter(brfss_df, response == "Very good") %>%
  group_by(state,year) %>%
  summarize(mean_prop = mean(data_value)) %>%
  ggplot(aes(x = year, y = mean_prop, color = state)) +
  geom_line() +
  theme(legend.position = "none")

aver_good = 
  filter(brfss_df, response == "Good") %>%
  group_by(state,year) %>%
  summarize(mean_prop = mean(data_value)) %>%
  ggplot(aes(x = year, y = mean_prop, color = state)) +
  geom_line() +
  theme(legend.position = "none")

aver_fair = 
  filter(brfss_df, response == "Fair") %>%
  group_by(state,year) %>%
  summarize(mean_prop = mean(data_value)) %>%
  ggplot(aes(x = year, y = mean_prop, color = state)) +
  geom_line() +
  theme(legend.position = "none")

aver_poor = 
  filter(brfss_df, response == "Poor") %>%
  group_by(state,year) %>%
  summarize(mean_prop = mean(data_value)) %>%
  ggplot(aes(x = year, y = mean_prop, color = state)) +
  geom_line() +
  theme(legend.position = "bottom")

aver_exce + aver_very + aver_good + aver_fair + aver_poor
```

    ## Warning: Removed 3 rows containing missing values (geom_path).

    ## Warning: Removed 2 rows containing missing values (geom_path).

    ## Warning: Removed 2 rows containing missing values (geom_path).

    ## Warning: Removed 1 rows containing missing values (geom_path).

    ## Warning: Removed 1 rows containing missing values (geom_path).

![](p8105_hw3_qs2200_files/figure-markdown_github/problem%201.5-1.png)

Problem 2
---------

**1. Import, explore and describe the dataset.**

``` r
instacart_df = p8105.datasets::instacart 
head(instacart_df)
```

    ## # A tibble: 6 x 15
    ##   order_id product_id add_to_cart_ord… reordered user_id eval_set
    ##      <int>      <int>            <int>     <int>   <int> <chr>   
    ## 1        1      49302                1         1  112108 train   
    ## 2        1      11109                2         1  112108 train   
    ## 3        1      10246                3         0  112108 train   
    ## 4        1      49683                4         0  112108 train   
    ## 5        1      43633                5         1  112108 train   
    ## 6        1      13176                6         0  112108 train   
    ## # ... with 9 more variables: order_number <int>, order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>,
    ## #   product_name <chr>, aisle_id <int>, department_id <int>, aisle <chr>,
    ## #   department <chr>

The dataset is about online purchase order in Instacart.

There are 15 variables in the dataset, in which the "eval\_set", "aisle", "product\_name", "department" are character variables, others are all integer variables.These variables contain the id and category of products in each order, the user and id of an order, the time each order is placed and the time each product is added to the cart and so on.

There are 1384617 observations in the dataset, each one represents a product in an order. For example, the first row in the dataset illustrate the order id is 1, the product id is 49302. It is the first product added in cart in order 1, and it has been reordered by the user 112108 in the past.This order belongs to the train evaluation set, and is the 4th order of the user. This order is placed on the 4th day of a week, 10 a.m., and it has been 9 days since last order was placed.The product is Bulgarian Yogurt, in dairy and egg department (id: 16), yogurt aisle(id: 120).

**2. How many aisles are there, and which aisles are the most items ordered from?**

``` r
aisle_max = as.data.frame(table(instacart_df$aisle))%>%
  filter(Freq == max(Freq)) 
```

There are 134 alsles there.The aisle "fresh vegetables" is the most items ordered from.

**3. Make a plot that shows the number of items ordered in each aisle. Order aisles sensibly, and organize your plot so others can read it.**

``` r
instacart_df %>%
  group_by(aisle, department) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = aisle, y = n))+
  geom_bar(stat="identity")+
  facet_wrap( ~ department,ncol = 3,scale = "free")
```

![](p8105_hw3_qs2200_files/figure-markdown_github/problem%202.3-1.png)

**4. Make a table showing the most popular item aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”.**

``` r
instacart_df %>%
  group_by(aisle, product_name) %>%
  summarize(item_number = n()) %>%
  filter(aisle %in% c("baking ingredients", "dog food care",  "packaged vegetables fruits")) %>%
  filter(item_number == max(item_number)) %>%
  knitr::kable(digits = 0)
```

| aisle                      | product\_name                                 |  item\_number|
|:---------------------------|:----------------------------------------------|-------------:|
| baking ingredients         | Light Brown Sugar                             |           499|
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |            30|
| packaged vegetables fruits | Organic Baby Spinach                          |          9784|

\`\`\`
